apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  namesapce: todoapp
spec:
  storageClassName: standard
  persistentVolumeClaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/